### ISSUE TITLE
Can't pick up drones if there are no drones in cargo

### ISSUE THREAD

**Issue by desmondkung** [Redacted-Games-LLC/Merchant-Empires#15]
Steps to reproduce:

1. Purchase 20 drones
2. Deploy 10 drones.
3. Pick up drones.
4. Deploy 20 drones.
5. Unable to pick up drones.

**Comment by Celdecea** [comment]
Resolved with https://github.com/Redacted-Games-LLC/Merchant-Empires/commit/634f904b9615f75febf1d1f8354049e2cfd42181.
