### ISSUE TITLE
Background flickers when in trade port menu

### ISSUE THREAD

**Issue by desmondkung** [Redacted-Games-LLC/Merchant-Empires#16]
The out-of-focus background has significant flickering when in trade port.
Have not isolated if it's just trade, or other ports are affected too.
Might require scrolling in trade menu to cause flickering -> Yet to determine actual cause.

**Comment by Celdecea** [comment]
Hmm, I can't reproduce on my system but I have an idea of what you could be seeing. The file [res/teal_dither.png](https://github.com/Redacted-Games-LLC/Merchant-Empires/blob/master/www/res/teal_dither.png) makes up the "blurred background" and is a 2x2 checkerboard that effectively covers 50% of the screen.  If your scroll mechanics are different from mine it make be making the background look glitchy.

Try the following image in its place and tell me if that fixes it or makes it better and I'll go from there. (Note it's a tiny dot under this paragraph, I can email it to you if you need).

![teal_dither](https://user-images.githubusercontent.com/881097/85089225-ea293000-b196-11ea-844b-c13580a973d1.png)

**Comment by desmondkung** [comment]
Yup, the replacement is a marked improvement on my laptop, but will probably only be able to confirm some time next weekend on a larger screen and with proper room lighting.

**Comment by Celdecea** [comment]
I believe this is fixed with [this commit](https://github.com/Redacted-Games-LLC/Merchant-Empires/commit/6a7e681dcca88195e8cdff90d57bf6a679f6f7d3)

**Comment by desmondkung** [comment]
Fix confirmed.
