### ISSUE TITLE
Star map moved off DSS

### ISSUE THREAD

**Issue by desmondkung** [Redacted-Games-LLC/Merchant-Empires#17]
![1](https://user-images.githubusercontent.com/3261081/85135629-f97cac00-b270-11ea-9d23-fd9352ddf96d.JPG)
![2](https://user-images.githubusercontent.com/3261081/85135633-faadd900-b270-11ea-9bb6-9be8fd2a6204.JPG)

Can't recall what I did that caused this to happen. Might be a fluke.
Closed the browser and re-opened again to fix it.
Didn't try logging off and on.

**Comment by Celdecea** [comment]
Did the DSS background actually shift over or are you just at a planet close to the edge?

**Comment by desmondkung** [comment]
Restricted

Great question. I don't remember actually.
I captured this a few days back and realized I didn't file a bug.

The sectors are in the pic, so I should be able to manipulate the db to get myself back there to take a look next week.

**Comment by Celdecea** [comment]
I believe this is fixed with [this commit](https://github.com/Redacted-Games-LLC/Merchant-Empires/commit/5dbd36756365df37beb3aad8cda6374890abfea1).

**Comment by desmondkung** [comment]
Nice. Fixed.

**Comment by desmondkung** [comment]
![WhatsApp Image 2020-06-20 at 08 24 30](https://user-images.githubusercontent.com/3261081/85187098-adad1f80-b2cf-11ea-81af-e2236958a03d.jpeg)
Not exactly the edge, but it's definitely there when I "teleported" back
