### ISSUE TITLE
Cannot 'break' 3 levels  in hndl/generate_galaxy.php on line 301

### ISSUE THREAD

**Issue by regnighc** [Redacted-Games-LLC/Merchant-Empires#6]
Hi @Celdecea 

The other issue I have is now when I click on 'Update' button to generate my first galaxy it goes to handler.php and gives an error 500. 
From the logs it shows this error: `PHP Fatal error:  Cannot 'break' 3 levels in /var/www/html/spacegame/hndl/generate_galaxy.php on line 301, referer: http://192.168.2.54/spacegame/admin.php?page=system `

Looking at the generate_galaxy.php file at line 301 it appears to be having a problem breaking 3

```
if (!($st = $db->get_db()->prepare("insert into places (caption, system, x, y, type) values (?,?,?,?,?)"))) {
				error_log(__FILE__ . '::' . __LINE__ . " Prepare failed: (" . $db->get_db()->errno . ") " . $db->get_db()->error);
				$return_codes[] = 1006;
				break 3;
			}
```

I'm not really that good with php, but probably something you will spot straight away.

**Comment by Celdecea** [comment]
Your line 301 doesn't match the code in GitHub, and your sample of code is ambiguous. Please check [this file](https://github.com/Redacted-Games-LLC/Merchant-Empires/blob/master/www/hndl/generate_galaxy.php#L272) and confirm line 272 is your problem.

Also please check your php error log and search for "301" near "Prepare Failed: " to find the SQL database error that is triggering the failure.

**Comment by regnighc** [comment]
Think I got it sorted,

1) I was using an old release and not the latest revision.

2) I was using php 7.2 which apparently doesn't support GD libraries, so I downgraded to 5.6 and so far things seem to be working.

**Comment by Celdecea** [comment]
Cool. Hope you enjoy the game! Sorry I never got around to finishing bases/base busting.
