### ISSUE TITLE
Good list no longer maintained

### ISSUE THREAD

**Issue by Badspler** [Redacted-Games-LLC/Merchant-Empires#7]
I am looking for the old goods list, in particular how the trade web worked. I believe from the project readme it should be downloaded from: http://merchantempires.net/host.php

However this domain no longer looks maintained or held by the project owners. 

I would be really appreciative if a copy of the database/goods list that you could be made available.

**Comment by Celdecea** [comment]
I may still have those files. Let me see what I can dig up.

**Comment by Badspler** [comment]
Any update?

**Comment by Celdecea** [comment]
Hello, I have located the [goods and ships files](https://www.dropbox.com/s/yaa6ffjbssu9279/round1_rel1.zip?dl=0). I will update the readme with this new link.

**Comment by Badspler** [comment]
Thanks a load @Celdecea
